Add `SimpleCov` and its configuration
sanG-github/Search-Analytics pull request #49
Opened 2022-10-12 03:19 UTC by sanG-github

- Resolve #48 

## Proof of change

<img width="1430" alt="Screen Shot 2022-10-12 at 09 46 11" src="https://user-images.githubusercontent.com/63148598/195241555-e78ef7c9-d735-49d7-8ab6-98e8d300cf13.png">

2022-10-14 02:25 UTC, rosle commented on Gemfile
> +  gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'main'
Just curious, why are we pointing to the main branch here? 💭

2022-10-14 02:26 UTC, rosle commented on config/environments/test.rb
> +  config.eager_load = true
Is this making it slow when running a test locally, not sure 🤔

2022-10-14 02:32 UTC, rosle commented on spec/rails_helper.rb
> +SimpleCov.start 'rails'
We usually have it in a separated support file, You can check it here 👍 - https://github.com/nimblehq/rails-templates/blob/7810d17896f9e5ba185adbf6e136d6bd237d5785/spec/support/simplecov.rb

2022-10-14 03:12 UTC, sanG-github commented on Gemfile
> +  gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'main'
@rosle 
No for any particular reasons, I just thought that will use the latest version (same as [the document](https://github.com/faker-ruby/faker#:~:text=your%20Gemfile%20to%3A-,gem%20%27faker%27%2C%20%3Agit%20%3D%3E%20%27https%3A//github.com/faker%2Druby/faker.git%27%2C%20%3Abranch%20%3D%3E%20%27main%27,-Usage)) of Faker gem.

2022-10-14 03:20 UTC, sanG-github commented on config/environments/test.rb
> +  config.eager_load = true
I have tried the default configuration that relies on `ENV["CI"]`. But I found that SimpleCov requires eager loading of all the code before starting tests. You can check it out [here](https://stackoverflow.com/questions/27833647/whats-the-impact-of-eager-load-true#:~:text=In%20test%20environment%20sometimes%20you%20just%20can%27t%20use%20eager_load%3Dfalse%20if%20you%20want%20to%20estimate%20some%20code%20metrics%20like%20code%20coverage%20or%20doing%20style%20checks.%20E.g.%20simple_cov%20requires%20you%20to%20eager%20load%20all%20the%20code%20before%20starting%20tests.).

2022-10-14 03:21 UTC, sanG-github commented on spec/rails_helper.rb
> +SimpleCov.start 'rails'
Thank you! 🥇 
I will separate it into another file.

2022-10-14 10:01 UTC, tyrro commented on Gemfile
> +  gem 'factory_bot_rails'
Our template encourages the [fabrication](https://vscode.dev/github.com/nimblehq/rails-templates/blob/6062b2b8c7e8685e38d45872e47211a7c6c6b69c/Gemfile.tt#L47-L48) gem, and we use it in the client projects too. I'd recommend getting used to using fabrication too...but I'd let you decide on this one 😉

2022-10-17 02:50 UTC, sanG-github commented on Gemfile
> +  gem 'factory_bot_rails'
That seems like we can use either [Fabrication or FactoryBot](https://nimblehq.co/compass/development/code-conventions/ruby/rspec/#:~:text=Use%20a%20gem%20like%20fabrication%20or%20factory_bot%20to%20reduce%20the%20verbosity%20when%20working%20with%20models.).  So I think `FactoryBot` still good, I will try `Fabrication` later, thank you for your suggestion!

2022-10-20 04:37 UTC, tyrro requested changes
Two small suggestions - 
- When resolving feedbacks, you might want to resolve comments mentioning the `commit_id` where it got resolved, you might want to go though [compass](https://nimblehq.co/compass/development/code-reviews/author-guidelines/#handle-comments-of-code-reviewers) regarding the conventions!
- When attaching pictures in PR description, you can use the following markdown to make it foldable, this way the PR description remains lean! 💡

```
<details><summary>Summary of the photo</summary>picture URL goes here</details>
```

2022-10-20 04:37 UTC, tyrro commented on spec/support/shoulda_matcher.rb
> +# frozen_string_literal: true
Could we be consistent with this line `frozen_string_literal: true`? In some of the files, we have it, in some we don't 😄

2022-10-20 04:37 UTC, tyrro commented on spec/factories/attachment.rb
> +    content { 10.times.map { FFaker::Name.name }.join(',') }
maybe we could use [paragraph](https://github.com/ffaker/ffaker/blob/main/lib/ffaker/lorem.rb#L37) 💡

```suggestion
    content { FFaker::Lorem.paragraph }
```

2022-10-20 07:09 UTC, sanG-github commented on spec/support/shoulda_matcher.rb
> +# frozen_string_literal: true
It's a good catch, I forgot to add this rule to `rubocop`.

2022-10-20 07:24 UTC, sanG-github commented on spec/factories/attachment.rb
> +    content { 10.times.map { FFaker::Name.name }.join(',') }
@tyrro
Thank you for your suggestion. In this case, I think using the old one is still good because the paragraph uses `' ' (space)` as a separator, and I need many words separated by a `',' (comma)`.

```
 def paragraph(sentence_count = 3)
      sentences(sentence_count + rand(0..2)).join(' ')
 end
```

2022-10-20 07:33 UTC, rosle approved these changes

2022-10-20 07:42 UTC, sanG-github commented on spec/support/shoulda_matcher.rb
> +# frozen_string_literal: true
Resolve in commit: [414889f](https://github.com/sanG-github/Search-Analytics/pull/49/commits/414889f1a5d70a0c6afd869d1546c3588e1a58b8)

2022-10-21 04:21 UTC, tyrro commented on Gemfile
> +  gem 'factory_bot_rails'
sure, works for me!

2022-10-21 04:23 UTC, tyrro approved these changes

2022-10-21 10:16 UTC, merged