Add unit tests for attachments controller
sanG-github/Search-Analytics pull request #50
Opened 2022-10-12 08:15 UTC by sanG-github

## What happened

We don't have any test cases for the attachments controller.

## Insight

Added test cases that cover three actions: `index`, `results`, and `create` in the happy case and worse case also.

2022-10-14 02:43 UTC, rosle commented on spec/controllers/attachments_controller_spec.rb
> +  before { sign_in user }
Usually we prefer to do this in explicitly on each test, you could check more here -> https://nimblehq.co/compass/development/code-conventions/ruby/rspec/#fixtures-isolation 👍

2022-10-14 02:43 UTC, rosle commented on spec/controllers/attachments_controller_spec.rb
> +    context 'not have any attachments' do
How about

```suggestion
    context 'when the user does not have any attachments' do
```

to be consistent with the test above

2022-10-14 02:43 UTC, rosle commented on spec/controllers/attachments_controller_spec.rb
> +      it 'redirect to the last attachment detail' do
```suggestion
      it 'redirects to the last attachment detail' do
```

2022-10-14 02:43 UTC, rosle commented on spec/controllers/attachments_controller_spec.rb
> +      it 'create a new attachment and redirect the the detail page' do
```suggestion
      it 'creates a new attachment and redirects to the detail page' do
```

Same for the test below

`it 'sends an error message by the worker' do`

2022-10-14 02:43 UTC, rosle commented on spec/controllers/attachments_controller_spec.rb
> +        expect(PushNotificationWorker.jobs.size).to eq(1)
Is it possible to also check for the error message? 🤔 💡

2022-10-14 03:23 UTC, sanG-github commented on spec/controllers/attachments_controller_spec.rb
> +        expect(PushNotificationWorker.jobs.size).to eq(1)
Yes, we also can check the error message here!

2022-10-20 04:56 UTC, tyrro commented
- Sidekiq has [renamed](https://github.com/mperham/sidekiq/discussions/4971) `Sidekiq::Worker` to `Sidekiq::Jobs`. Do we want to rename the `app/worker` to `app/jobs` as well? Sidekiq wiki seems to use the [job](https://github.com/mperham/sidekiq/wiki/Getting-Started#rails) prefix as well!
- We seem to have both `spec` and `test` folder. Do we have a reason to keep both?

2022-10-20 05:09 UTC, tyrro requested changes

2022-10-20 05:09 UTC, tyrro commented on spec/controllers/attachments_controller_spec.rb
> +    context 'when upload valid file' do
could we rewrite it for better readability?
```suggestion
    context 'when a valid file is uploaded' do
```

2022-10-20 05:09 UTC, tyrro commented on spec/controllers/attachments_controller_spec.rb
> +    context 'when upload invalid file' do
ditto

```suggestion
    context 'when an invalid file is uploaded' do
```

2022-10-20 07:37 UTC, rosle approved these changes

2022-10-20 07:37 UTC, rosle commented on spec/controllers/attachments_controller_spec.rb
> +    it 'renders the page with instance variables' do
Instead of this I prefer something like `renders the page with user attachments ordered by created_at DESC` I think it would be clearer. What do you think? 💭

2022-10-20 07:47 UTC, sanG-github commented on spec/controllers/attachments_controller_spec.rb
> +    it 'renders the page with instance variables' do
Yeah, thank you for pointing this out. I also think it's a more informative message than the previous one.

2022-10-20 07:53 UTC, sanG-github commented
@tyrro 

> Sidekiq has https://github.com/mperham/sidekiq/discussions/4971 Sidekiq::Worker to Sidekiq::Jobs. Do we want to rename the app/worker to app/jobs as well? Sidekiq wiki seems to use the [job](https://github.com/mperham/sidekiq/wiki/Getting-Started#rails) prefix as well!

Good catch 👍, Olivier also has already mentioned this issue [here](https://github.com/sanG-github/Search-Analytics/issues/32). But this PR is focused on writing test cases, so for improvement, I think it is more suitable to create a new PR and resolve this issue.

> We seem to have both spec and test folder. Do we have a reason to keep both?

There is no reason, I will delete the default test folder of rails. Thank you 🙆‍♂️

2022-10-21 04:24 UTC, tyrro approved these changes

2022-10-21 10:44 UTC, merged