[#46][Backend] Add test for results controller (external api)
sanG-github/Search-Analytics pull request #52
Opened 2022-10-14 04:09 UTC by sanG-github

Resolve #46 

## Why

Currently, we don't have tests for external `results_controller`, as a developer, we need to improve the code coverage of the controller to 100%

## Acceptance Criteria

- Add unit tests for list results in case filtered by keyword or not
- Add unit tests for result detail
- Add unit tests to get keywords of user

## Proof of Work

![Screen Shot 2022-10-14 at 11 03 40](https://user-images.githubusercontent.com/63148598/195759883-3be4d6fc-878f-4182-80c1-0c3b2b9d19d0.png)

2022-10-21 05:00 UTC, tyrro requested changes

2022-10-21 05:00 UTC, tyrro commented on spec/controller/api/v1/results_controller_spec.rb
> +        returned_result = user.results.to_json
- Do we need to create a `user` here? We can use the `user` of the attachment right?
```ruby
attachment = create :attachment
user = attachment.user
```
-  Instead of checking `user.results` as expected output, what about creating a bunch of `results` and checking whether the output matches it? This way result does not become attached to any `user` object
```ruby
results = create_list :result, number_of_result, attachment: attachment
expect(response.body).to eq(result)
```

2022-12-20 06:40 UTC, sanG-github commented on spec/controller/api/v1/results_controller_spec.rb
> +        returned_result = user.results.to_json
Updated it in 3d5e03a ✅

2023-01-30 08:49 UTC, tyrro requested changes

2023-01-30 08:49 UTC, tyrro commented on spec/controller/api/v1/results_controller_spec.rb
> +        result = JSON.parse(response.body)
what about reusing the existing [`json_response`](https://github.com/sanG-github/Search-Analytics/blob/develop/spec/support/request_helpers.rb#L5-L7)  helper you already created before 😉

2023-01-30 08:49 UTC, tyrro commented on spec/controller/api/v1/results_controller_spec.rb
> +        result = JSON.parse(response.body)
ditto here if we agree on the previous comment! 🙌🏽

2023-02-07 01:31 UTC, byhbt approved these changes
LGTM along with tyrro comment

2023-02-07 03:00 UTC, sanG-github commented on spec/controller/api/v1/results_controller_spec.rb
> +        result = JSON.parse(response.body)
Updated it in b3def73 ✅, I don't even remember this method 😂

2023-02-27 06:25 UTC, tyrro approved these changes

2023-02-27 23:51 UTC, merged