[#45][Backend] Add test for attachments controller (external api)
sanG-github/Search-Analytics pull request #53
Opened 2022-10-14 07:09 UTC by sanG-github

Resolve #45 

## What happened

We don't have any test cases for the attachments controller.

## Insight

Write test cases to create an attachment and also scrape data from google, in the worst case, the error happens, it returns an error message to the user.

## Proof of Work

![Screen Shot 2022-10-14 at 14 05 38](https://user-images.githubusercontent.com/63148598/195783881-caff855a-4b94-485e-a1a3-85da1d4ce3ef.png)

2022-10-21 05:11 UTC, tyrro requested changes

2022-10-21 05:11 UTC, tyrro commented on spec/controllers/api/v1/attachments_controller_spec.rb
> +        result = JSON.parse(response.body)
Instead of repeating it, we can use a [helper](https://github.com/nimblehq/rails-templates/blob/develop/spec/support/request_helpers.rb) from our rails template 💡

2022-10-21 05:11 UTC, tyrro commented on spec/controllers/api/v1/attachments_controller_spec.rb
> +    context 'when upload valid file' do
```suggestion
    context 'when a valid file is uploaded' do
```

2022-10-21 05:11 UTC, tyrro commented on spec/controllers/api/v1/attachments_controller_spec.rb
> +        allow_any_instance_of(Attachments::CreateService).to receive(:call).and_raise(StandardError, error_message)
We follow the `arrange-act-assert` paradigm(more in [compass](https://nimblehq.co/compass/development/code-conventions/ruby/rspec/#convention-15)), could we follow it here too?

```ruby
        # arrange
        user = create :user
        error_message = "Error message test"
        allow_any_instance_of(Attachments::CreateService).to receive(:call).and_raise(StandardError, error_message)

        #act
        sign_in user
```

2022-12-18 11:41 UTC, sanG-github commented on spec/controllers/api/v1/attachments_controller_spec.rb
> +        result = JSON.parse(response.body)
Really helpful 😄 Thank you!

e5bc0e8 ✅

2022-12-18 11:41 UTC, sanG-github commented on spec/controllers/api/v1/attachments_controller_spec.rb
> +        allow_any_instance_of(Attachments::CreateService).to receive(:call).and_raise(StandardError, error_message)
Updated it in 6d44960 ✅

2022-12-29 03:25 UTC, rosle approved these changes

2022-12-29 03:25 UTC, rosle commented on spec/controllers/api/v1/attachments_controller_spec.rb
> +    context 'when receive a StandardError from service' do
how about:
```suggestion
    context 'when receiving a StandardError from the Attachments::CreateService' do
```
- `receive` -> `receiving` - to correct the grammar
- `service` -> `the Attachments::CreateService` to make the context clearer

2023-01-03 01:57 UTC, sanG-github commented on spec/controllers/api/v1/attachments_controller_spec.rb
> +    context 'when receive a StandardError from service' do
Updated it in 1d0a19d ✅

2023-01-17 04:34 UTC, byhbt approved these changes

2023-01-17 04:35 UTC, merged