41 setup ci
sanG-github/Search-Analytics pull request #55
Opened 2022-10-17 04:57 UTC by sanG-github

2022-10-20 07:52 UTC, rosle commented on .github/workflows/ci.yml
> +name: "CI"
Maybe without double quote to be consistent with other places
 
```suggestion
name: CI
```

And I'm thinking of maybe more specific name. For example, this is to run test, we could call `workflows/test` with `name: Test` just to be clear 💭 💡

2022-10-20 07:52 UTC, rosle commented on .github/workflows/ci.yml
> +        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
Can't we use the version number directly 🤔 💭 `ruby/setup-ruby@1.115.3`

2022-10-20 07:52 UTC, rosle commented on .github/workflows/ci.yml
> +  lint:
I would prefer this to come first before `test` job 💡

2022-10-20 07:52 UTC, rosle commented on .rubocop.yml
> +AllCops:
For this rubocop, I would recommend to grab it from our rails template to ensure the same rules applied on this project 😆 👍  

https://github.com/nimblehq/rails-templates/blob/develop/.rubocop.yml

2022-10-20 08:58 UTC, sanG-github commented on .github/workflows/ci.yml
> +        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
Yeah, it's okay to use `ruby/setup-ruby@v1`, but when I tried with `ruby/setup-ruby@1.115.3`, strange thing happened 😨😨

![image](https://user-images.githubusercontent.com/63148598/196904135-bce93e4b-1559-4478-8697-3605d6c3621c.png)

2022-10-20 08:58 UTC, sanG-github commented on .rubocop.yml
> +AllCops:
Resolved in commit: [e4af7c7](https://github.com/sanG-github/Search-Analytics/pull/55/commits/e4af7c73ce0011ca1af90e80da2efbd122cba061)

2022-10-20 08:58 UTC, sanG-github commented on .github/workflows/ci.yml
> +  lint:
Resolved in commit: [e4af7c7](https://github.com/sanG-github/Search-Analytics/pull/55/commits/e4af7c73ce0011ca1af90e80da2efbd122cba061)

2022-10-20 08:59 UTC, sanG-github commented on .github/workflows/ci.yml
> +name: "CI"
Resolved in commit: [e4af7c7](https://github.com/sanG-github/Search-Analytics/pull/55/commits/e4af7c73ce0011ca1af90e80da2efbd122cba061)

2022-10-20 08:59 UTC, sanG-github commented on .github/workflows/ci.yml
> +        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
Resolved in commit: [d0388e7](https://github.com/sanG-github/Search-Analytics/pull/55/commits/d0388e7191103e2e3b879f628698e48c4329d2ba)

2022-10-21 02:47 UTC, rosle commented on .rubocop.yml
> +AllCops:
@sanG-github I still see this file is different from the template. Do you have any issues after applying it? 💭

2022-10-21 02:49 UTC, rosle commented on .github/workflows/test.yml
> +# This workflow uses actions that are not certified by GitHub.  They are
```suggestion
# This workflow uses actions that are not certified by GitHub. They are
```

2022-10-21 03:37 UTC, sanG-github commented on .rubocop.yml
> +AllCops:
@rosle
I just change a part of the rules: `AllCops`. Because I also change many files based on the changes of rubocop.yml [here](https://github.com/sanG-github/Search-Analytics/pull/49/commits/414889f1a5d70a0c6afd869d1546c3588e1a58b8). I think we can resolve it after [this PR](https://github.com/sanG-github/Search-Analytics/pull/49).

2022-10-21 05:16 UTC, tyrro requested changes

2022-10-21 05:16 UTC, tyrro commented on app/models/result.rb
> +    where('keyword LIKE ?', '%' + keyword + '%')
Does it fix this Rubocop error without disabling the rule? 🤔 

```suggestion
    where('keyword LIKE ?', "%#{keyword}%")
```

2022-10-21 05:40 UTC, rosle commented on .rubocop.yml
> +AllCops:
Got it 🙆‍♀️

2022-10-21 05:41 UTC, rosle approved these changes

2023-01-19 08:12 UTC, sanG-github commented on app/models/result.rb
> +    where('keyword LIKE ?', '%' + keyword + '%')
Updated in f911c64 ✅

2023-02-27 06:19 UTC, tyrro approved these changes

2023-02-27 06:19 UTC, tyrro commented on .github/workflows/test.yml
> +        run: bundle exec rspec spec
does it work without specifying the folder name? 🤔 

```suggestion
        run: bundle exec rspec
```

2023-02-27 23:52 UTC, merged